# Generated by Django 5.1.6 on 2025-02-22 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descrpiption',
            new_name='description',
        ),
    ]
